language: python
python:
  - "3.7-dev"  # 3.7 development branch
install:
  - pip install .[test]
  - install_antlrjar
# command to run tests
script:
  - export ANTLR4_JAR=jars/antlr-4.7.2-complete.jar && ./bin/tests